Hm 4 tests
denisyarinskih2/nodeJs pull request #4
Opened 2024-03-09 18:06 UTC by denisyarinskih2

2024-03-13 20:24 UTC, StepanPG requested changes

2024-03-13 20:24 UTC, StepanPG commented on jest.config.js
> +  transform: {
Please add coverage threshold with at least 85%

2024-03-15 13:50 UTC, denisyarinskih2 commented on jest.config.js
> +  transform: {
done

2024-03-15 15:10 UTC, StepanPG approved these changes

2024-03-15 15:24 UTC, merged